### ISSUE TITLE
Question regarding maxWait

### ISSUE THREAD

**Issue by zoell** [jesucarr/tokenbucket#3]
May I please have some more description on the maxWait parameter? Could you please explain a bit more via an example? From the description and examples it is not really clear to me what it does.
Thanks!

**Comment by jes-carr** [comment]
Let's say you have a bucket size 10, currently empty, which adds one token every minute. If you request 5 tokens, you will have to wait 5 minutes until you have enough tokens. But if it has a maxWait of 3 minutes, it won't wait more than 3 minutes, so you will get an error. 

Hope that example makes it clear.
